### ISSUE TITLE
Is there a way to add legend?

### ISSUE THREAD

**Issue by SaoYan** [HarisIqbal88/PlotNeuralNet#1]
Hi, I wonder if there is a way of adding legend to the figure (identifying which color corresponds to which type of layer).

A example would like the original U-Net figure:

<img width="639" alt="screen shot 2018-11-29 at 12 37 17 am" src="https://user-images.githubusercontent.com/25550286/49209371-26a3f980-f36f-11e8-9e76-1a34081697df.png">

**Comment by SaoYan** [comment]
Never mind~ I figured it out myself~

**Comment by quinwu** [comment]
> Never mind~ I figured it out myself~

I want to know how to add legend . Thanks

**Comment by ChengxiHAN** [comment]
Do you finish U-Net figure?
