### ISSUE TITLE
Drawing the kernel dimensions in a conv layer

### ISSUE THREAD

**Issue by mvalstar** [HarisIqbal88/PlotNeuralNet#10]
Hi,

Great library, very useful. I am writing a book for Cambridge University Press and would like to use it to explain CNNs. One feature that's missing is drawing the kernel dimensions (e.g. 3x3 or 5x5 or 11x11). Do you have any suggestions how to do that?

Michel

**Comment by HarisIqbal88** [comment]
Hi, 
Thank you for the compliment.
Currently, this feature is not present in my code. However, you can use the low level tikz to do so. You might have to do something like [this](https://github.com/HarisIqbal88/PlotNeuralNet/blob/595cd2b4fec25fe0ded40e9da7b86b5be4f575d6/examples/VGG16/vgg16.tex#L95) to draw box to represent kernel and then, label it
