### ISSUE TITLE
How should I cite this?

### ISSUE THREAD

**Issue by kristiantorres** [HarisIqbal88/PlotNeuralNet#140]

**Comment by kristiantorres** [comment]
I just found out on the zenodo website. You could incorporate this in the README.md. 

Haris Iqbal. (2018). HarisIqbal88/PlotNeuralNet v1.0.0 (v1.0.0). Zenodo. https://doi.org/10.5281/zenodo.2526396

**Comment by Lin-Yux** [comment]
Thank u for your sharing, it's really helpful !
