### ISSUE TITLE
pdflatex + evince error

### ISSUE THREAD

**Issue by FloraSaysGoodmorning** [HarisIqbal88/PlotNeuralNet#16]
Hi awesome team, 
I was trying to run example in the readme, was able to get the latex printed out in terminal but...
```
../tikzmake.sh: line 5: pdflatex: command not found
rm: *.aux: No such file or directory
rm: *.log: No such file or directory
rm: *.vscodeLog: No such file or directory
../tikzmake.sh: line 10: evince: command not found
line 5: pdflatex: command not found
```
Is there a way to not use these two?

**Comment by HarisIqbal88** [comment]
The code is primarily written in Latex(with python wrapper). If you have a different compiler for latex than pdflatex, then try compiling the code in examples directory with your latex compiler. As for evince,  you can use [#14](https://github.com/HarisIqbal88/PlotNeuralNet/issues/14#issue-412737661)
