### ISSUE TITLE
Drawing only one conv layer

### ISSUE THREAD

**Issue by amirhfarzaneh** [HarisIqbal88/PlotNeuralNet#22]
Hello, 
thank you for this awesome project. If I draw only one conv layer like this:
```
\pic[shift={(0,0,0)}] at (0,0,0) {RightBandedBox={name=cr1,caption=conv1,%
        xlabel={{"96", ""}},ylabel=224,zlabel=224,fill=\ConvColor,bandfill=\ConvReluColor,%
        height=40,width={2},depth=40}};
```
then I have to keep xlabel as ` xlabel={{"96", ""}}` with an empty qoutation marks. Is there a way to eliminate this need?

**Comment by HarisIqbal88** [comment]
I couldn't solve this any other way. If you found a way, please share
