### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by baurst** [HarisIqbal88/PlotNeuralNet#3]
Hi, 
first of all let me say the visualization you have created here is looking excellent! I was thinking about using it, but I have noticed that there is no license included in the project. Could you please add one? You could check out [choosealicense.com](https://choosealicense.com) if you are unsure which license fits your needs.
Thank you very much.

**Comment by HarisIqbal88** [comment]
thanks for pointing it out. I have added a license now.
