### ISSUE TITLE
unet error 

### ISSUE THREAD

**Issue by wm901115nwpu** [HarisIqbal88/PlotNeuralNet#30]
pyexamples|master⚡ ⇒ bash ../tikzmake.sh unet

  File "unet.py", line 19
    *block_2ConvPool( name='b2', botton='pool_b1', top='pool_b2', s_filer=256, n_filer=128, offset="(1,0,0)", size=(32,32,3.5), opacity=0.5 ),
    ^
SyntaxError: invalid syntax
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `unet.tex'.
<*> unet.tex

(Press Enter to retry, or Control-D to exit)
Please type another input file name: ^D
! Emergency stop.
<*> unet.tex

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.
rm: *.aux: No such file or directory
rm: *.vscodeLog: No such file or directory
rm: *.tex: No such file or directory
../tikzmake.sh: line 10: xdg-open: command not found

**Comment by efournie** [comment]
Hi,

I got the same issue on Ubuntu 18.04, it is probably caused by the use of python 2 as a default.

You can install python 3 with `apt install python3.6` and the replace `python $1.py` with `python3.6 $1.py in tikzmake.sh`

**Comment by AllenHigh** [comment]
@efournie Thanks a lot, I've solved the same question with your help.

**Comment by mrgloom** [comment]
Replace `python` with `python3` is sufficient.

**Comment by Viet0904** [comment]
> Chào bạn
> 
> Tôi gặp vấn đề tương tự trên Ubuntu 18.04, có lẽ do việc sử dụng python 2 làm mặc định.
> 
> Bạn có thể cài đặt python 3 với và thay thế bằng `apt install python3.6``python $1.py``python3.6 $1.py in tikzmake.sh`

I also have the same problem, but I use Windows, how can I solve it?
