### ISSUE TITLE
ModuleNotFoundError: No module named 'pycore.tikzeng'

### ISSUE THREAD

**Issue by amirubin87** [HarisIqbal88/PlotNeuralNet#34]
After running 
`pip install pycore`
when I try to run in python:
`from pycore.tikzeng import *`
I got:
`ModuleNotFoundError: No module named 'pycore.tikzeng'`

Version: pycore==17.4.17

**Comment by JackKenney** [comment]
`pip uninstall pycore`

The `pycore` package referred to is the local one.

**Comment by veonua** [comment]
maybe it's worth to rename the package and publish it to Python Package Index ?

**Comment by shirui-japina** [comment]
I got `ModuleNotFoundError: No module named 'pycore'` after `pip uninstall pycore`...What am I doing wrong?

**Comment by shirui-japina** [comment]
> I got `ModuleNotFoundError: No module named 'pycore'` after `pip uninstall pycore`...What am I doing wrong?

Just forgot the code `cd pyexamples/`. My too low-level mistake.
