### ISSUE TITLE
Anyone would describe the requirements or dependencies?

### ISSUE THREAD

**Issue by 2ndMessiah** [HarisIqbal88/PlotNeuralNet#39]
Thanks to devs for developing this useful library.
However, I'm a pure layman to latex. Is there any version check for latex or some required python libraries?

TY.

**Comment by JGuillaumin** [comment]
With Ubuntu 16.04, default versions of `texlive-latex-base` and `texlive-latex-extra` are compatible.
And this project requires Python3.  (not 2.7).

**Comment by John1231983** [comment]
Use this 
```
sudo apt-get install texlive-latex-extra
```
