### ISSUE TITLE
Font size in the graph

### ISSUE THREAD

**Issue by MofiiTech** [HarisIqbal88/PlotNeuralNet#43]
Does anyone know how to change the font size in the graph? I tried to simply add to the documentclass

`\documentclass[border=15pt, multi, tikz]{standalone}`

but it doesn't work and returns some errors with positioning.

**Comment by guillermo-jimenez** [comment]
A temporal solution would be to change the files Box.sty and RightBandedBox.

In both files there's a line that states:

```
\path (b) edge ["\xlabel"',midway] (c);
```

I changed these lines to:

```
\path (b) edge ["\Huge\xlabel"',midway] (c);
```

Also, there's a line that states:

```
\path (c) edge ["\small\zlabel"',depthlabel](f); %depth label
```

I changed these lines to:

```
\path (c) edge ["\Large\zlabel"',depthlabel](f); %depth label
```

Hope it helps.

Regards,
Guille

**Comment by HarisIqbal88** [comment]
As far as I remember, increasing the scale parameter and then decreasing value for depth,height and width by same scale does the trick

**Comment by MofiiTech** [comment]
> As far as I remember, increasing the scale parameter and then decreasing value for depth,height and width by same scale does the trick

This works for me. Thank you!
