### ISSUE TITLE
to_input(...) doesn't have east, west... properties

### ISSUE THREAD

**Issue by dougsouza** [HarisIqbal88/PlotNeuralNet#46]
I would like to connect the input image to conv blocks and other blocks, but it is not possible since `to_input(...)` doesn't have east, west, northeast, etc... properties. How to solve this? Maybe wrap `to_input(...)` in a box or something?

**Comment by rafariva** [comment]
i have the same issue, please any help¿?

**Comment by dougsouza** [comment]
@rafariva, there is a way: describe your model directly in latex syntax (no python wrapper) and plot an invisible box over the input layer, then you can connect arrows to that invisible box.

**Comment by rafariva** [comment]
Please, can you send us an short example?

**Comment by dougsouza** [comment]
@rafariva, I don't have an example specific for this. You could just follow this: [https://github.com/HarisIqbal88/PlotNeuralNet/blob/master/examples/fcn8s/fcn8.tex](https://github.com/HarisIqbal88/PlotNeuralNet/blob/master/examples/fcn8s/fcn8.tex)

Once you get the syntax, it is not difficult

**Comment by rafariva** [comment]
Thant 4 u help
