### ISSUE TITLE
【help】HED 

### ISSUE THREAD

**Issue by Ysoleil** [HarisIqbal88/PlotNeuralNet#47]
Thank you very much for your great work.
I want to draw the network structure of HED, but it has not been successful for a long time. 
Can anyone share the original code of drawing HED? The deadline is coming. T-T
I'll be grateful.

**Comment by Iron4dam** [comment]
Same here.

**Comment by HarisIqbal88** [comment]
You can find code for HED [here](https://github.com/HarisIqbal88/PlotNeuralNet/tree/master/examples/HED).
