### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by azadastro** [HarisIqbal88/PlotNeuralNet#49]
Hello
How do you want us to cite your work?

**Comment by maybe-hello-world** [comment]
As I understood, there's a link to zenodo.org, where I found this examaple:
Haris Iqbal. (2018, December 25). HarisIqbal88/PlotNeuralNet v1.0.0 (Version v1.0.0). Zenodo. http://doi.org/10.5281/zenodo.2526396
@misc{haris_iqbal_2018_2526396,
  author       = {Haris Iqbal},
  title        = {HarisIqbal88/PlotNeuralNet v1.0.0},
  month        = dec,
  year         = 2018,
  doi          = {10.5281/zenodo.2526396},
  url          = {https://doi.org/10.5281/zenodo.2526396}
}
