### ISSUE TITLE
May you add an example for U-Net?

### ISSUE THREAD

**Issue by panovr** [HarisIqbal88/PlotNeuralNet#5]
May you add an example for [U-Net](https://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/) architecture?
Thanks!

**Comment by HarisIqbal88** [comment]
I have added example made with new code format as well. You can also look an example in old format from commit before Dec 20, 2018. Note that I did not make it in Ushape because I needed it in this particular form. You can play around with code to fit your requirements.

**Comment by panovr** [comment]
@HarisIqbal88 Awesome, thanks!

**Comment by TixiaoShan** [comment]
@HarisIqbal88 
Happy New Year!

**Comment by HarisIqbal88** [comment]
@TixiaoShan 
Happy New Year!

**Comment by AtharvaMuley** [comment]
I am having difficulty building UNet using python. The layers do not stack up well Can you provide a python example?
