### ISSUE TITLE
Unet to DenseNets

### ISSUE THREAD

**Issue by zuxfoucault** [HarisIqbal88/PlotNeuralNet#50]
I am trying to modify Unet tex code to create DenseNets block.
![f838717a-6ad1-11e6-9391-f0906c80bc1d](https://user-images.githubusercontent.com/3050531/59554071-a4101e00-8fd0-11e9-9f3e-eb5a2485ba61.jpg)

I am wondering how to modify the connection lines that then look like densenets style?
Thank you for your time!

**Comment by zuxfoucault** [comment]
I modified HED and made it look a bit similar to DenseNet Block.
https://github.com/zuxfoucault/PlotNeuralNet/blob/master/examples/densenetblock/densenet.tex

**Comment by Banyueqin** [comment]
@zuxfoucault 
Can you tell me the python code abount the HED.Thanks.

**Comment by jiongzhang** [comment]
> I modified HED and made it look a bit similar to DenseNet Block.
> https://github.com/zuxfoucault/PlotNeuralNet/blob/master/examples/densenetblock/densenet.tex

Would you mind to share the setting for "\ConnColorA" "\ConnColorB" ... "\ConnColorD" , and "\midarrowA" ... "\midarrowC" in your source file? I couldn't find those settings in the whole package. Thanks

**Comment by zuxfoucault** [comment]
@jzhang55995 sorry for the late reply, here are the settings https://github.com/zuxfoucault/PlotNeuralNet/blob/master/layers/init.tex#L6

@Banyueqin sorry, I didn't modify the python part.
