### ISSUE TITLE
Way to change the fontsize

### ISSUE THREAD

**Issue by stillarrow** [HarisIqbal88/PlotNeuralNet#57]
Hi, thank you for this awesome project! I am new to LaTex and just wondering is there any way for me to define or change the fontsize for the caption or the depthlabel? Thanks you!

**Comment by mekaneeky** [comment]
Check https://github.com/HarisIqbal88/PlotNeuralNet/issues/43

**Comment by CoulsonZhao** [comment]
The [https://github.com/HarisIqbal88/PlotNeuralNet/issues/43](url) didn't answer the font of caption. If you need, you can change the `edge ["\textcolor{black}{ \bf \caption}"',captionlabel](cap)`  into  `edge ["\textcolor{black}{ \bf \huge\caption}"',captionlabel](cap)` in both Boxx.sty and Ball.sty

**Comment by CoulsonZhao** [comment]
The [https://github.com/HarisIqbal88/PlotNeuralNet/issues/43](url) didn't answer the font of caption. If you need, you can change the
 `edge ["\textcolor{black}{ \bf \caption}"',captionlabel](cap)`  
into
  `edge ["\textcolor{black}{ \bf \huge\caption}"',captionlabel](cap)` 
in both Boxx.sty and Ball.sty
