### ISSUE TITLE
What does the single quotation mark which follows double quotation marks mean?

### ISSUE THREAD

**Issue by OmegaNJU** [HarisIqbal88/PlotNeuralNet#6]
Thanks for your amazing work!
I am confused with the quotation mark like `"\cubezlabel"'`. What is the difference between `"\cubezlabel"`.

Looking forwarding your answer:)

**Comment by HarisIqbal88** [comment]
First of all, I would suggest you to have a look at the updated code. I made a lot of changes to make it easy to read and extend, especially in the layers directory.

As for your question, my understanding is that it toggles position of text with respect to its anchor node. For example, if ```"text"``` is at north(or west) of its anchor, then ```"text"'``` is at south(or east). Try playing with the following code to understand better: 
```
\documentclass[border=15pt, multi, tikz]{standalone}
\usetikzlibrary{positioning}
\usetikzlibrary{quotes,arrows.meta}

\begin{document}
\begin{tikzpicture}

\coordinate (a) at (0 , 0 , 0);
\coordinate (b) at (0 , 4 , 0);       
\path (a) edge["Some Lengthy text that has no meaning %
                at all in the larger scheme of life."',%
                pos=1,%
                text width=50,%
                text centered,%
                sloped] (b); 

\end{tikzpicture}
\end{document}
```

**Comment by OmegaNJU** [comment]
Yep! Thanks for your reply!
The updated code is amazing! And it's exactly what I want to do. I spent almost one week to read the tutorials in TiKz documentation and read all your old version code. I'm so happy that I really learned a lot.
By the way, if I use your code for drawing neural network which then be published, should I refer this repo and how could it be referred?
