### ISSUE TITLE
How to draw a multiple inputs model?

### ISSUE THREAD

**Issue by shirui-japina** [HarisIqbal88/PlotNeuralNet#61]
I want to draw a model with 3 convolutional layer inputs and Integrated into the fully connected layer.How can I do this?

**Comment by shirui-japina** [comment]
The solution I thought of is by setting the value of _**offset**_ to adjust the position of the image. Is this the best way to achieve this?

**Comment by kondela** [comment]
> The solution I thought of is by setting the value of _**offset**_ to adjust the position of the image. Is this the best way to achieve this?

So were you able to do it that way @shirui-japina ?

**Comment by zhou-rui1** [comment]
how to do that, I want to draw two parallel on one page too!
