### ISSUE TITLE
install on windows

### ISSUE THREAD

**Issue by cploveflower** [HarisIqbal88/PlotNeuralNet#66]
Hello!
@HarisIqbal88 
now I want to install the software to draw a picture for CNN network,can you tell me whether it can be installed on windows?Thank you very much!

**Comment by HarisIqbal88** [comment]
Haven't tested it but I think you can do it if you install the requisites mentioned in readme

**Comment by jackyko1991** [comment]
A pull requested https://github.com/HarisIqbal88/PlotNeuralNet/pull/72 is created for this issue
