### ISSUE TITLE
Labeling Blocks will create a solid line

### ISSUE THREAD

**Issue by OmegaNJU** [HarisIqbal88/PlotNeuralNet#7]
I tried to let the Box block's edges be invisible via `fill=\fill, draw=\fill` in Box.sty.

Actually, It only let edges AH, AD, DE, CD, EF and HE invisible.

Finally I found that `\path (b) edge ["\bf\xlabel"', midway] (c);` created a solid line in BC, so do AB and CF.

I have no idea to fix this and I don't know why the solid lines emerged though no pic action acted in above code.

Furthermore, I want customize the style of draw line, but nothing changes after I put `thin` into "box" style setting.

**Comment by OmegaNJU** [comment]
My latex environment is Mactex 2017, does it matter?

**Comment by HarisIqbal88** [comment]
> I tried to let the Box block's edges be invisible via fill=\fill, draw=\fill in Box.sty.

It does not make the edge invisible, it makes it the same colour as the fill. This is not important if opacity is high, but try with a low opacity and you get the your edges visible.

> Finally I found that \path (b) edge ["\bf\xlabel"', midway] (c); created a solid line in BC, so do AB and CF.

Yes, in my code every edge that is there to create a label(except for caption) also creates an edge.

> I don't know why the solid lines emerged though no pic action acted in above code.

As far as I understand, it is the default behaviour of the ```edge``` which you will notice if you run the code below. If you want to remove edges, I can think of 2 ways:
```tex
\documentclass[border=15pt, multi, tikz]{standalone}
\usetikzlibrary{quotes}

\begin{document}
\begin{tikzpicture}
% With Visible Edge 
\path (0,0,0) edge["Some text 1."',pos=0.5,text width=50,text centered] (4,0,0); 
% With edge opacity=0
\path (0,1,0) edge["Some text 2."',pos=0.5,text width=50,text centered, opacity=0, text opacity=1] (4,1,0); 
% With edge between 1 node
\path (0,2,0) edge["Some text 3."',text width=50,text centered] (0,2,0);
 
\end{tikzpicture}
\end{document}
```

**Comment by OmegaNJU** [comment]
Yes, these help me a lot. Thanks!

**Comment by martinlindstrom** [comment]
Hi @HarisIqbal88, cheers for the package, it has saved me a lot of headache drawing neural networks.

For posterity, I would like to add that the dot is present for me on Texmaker (PDFLaTeX)+Ubuntu, but disappears when the following lines from Box.sty are commented out:

> \tikzstyle{captionlabel}=[text width=15*\LastEastx/\scale,text centered]       
\path (\LastEastx/2,-\y/2,+\z/2) + (0,-25pt) coordinate (cap) 
edge [](cap) ; %Block caption/pic object label

**Comment by martinlindstrom** [comment]
Hi @HarisIqbal88 and cheers for a lovely package, it has saved me much headache drawing neural networks. 

I also see the black dot with Texmaker (PDFLaTeX) on Ubuntu when I am not using a caption for a Box. I found that if you comment out the following three lines from Box.sty the problem disappears.

`\tikzstyle{captionlabel}=[text width=15*\LastEastx/\scale,text centered]       
        \path (\LastEastx/2,-\y/2,+\z/2) + (0,-25pt) coordinate (cap) 
        edge ["\textcolor{black}{ \bf \caption}"',captionlabel](cap) ; %Block caption/pic object label`
