### ISSUE TITLE
Captioning the box will create a black dot only shown on Windows

### ISSUE THREAD

**Issue by OmegaNJU** [HarisIqbal88/PlotNeuralNet#8]
Hi, @HarisIqbal88 

I am back again 😸 ! I found that labeling a caption will make a black dot by the following code. Though it's invisible on my Mac OS and Ubuntu, I found it when I open the pdf on Windows, using Adobe reader exactly.

```
\path (\LastEastx/2,-\y/2,+\z/2) + (0,-25pt) coordinate (cap) 
        edge ["\textcolor{black}{ \bf \caption}"',captionlabel](cap) ; %Block caption/pic object label
```

I am wondering that the way you make labels by adding a edge, but the tutorials in TiKz always use `node`, which seems malfunctioned in your repo. (Maybe I use the `node` syntax wrongly)

![default](https://user-images.githubusercontent.com/5026687/50622153-22f32c00-0f46-11e9-8845-f06ca8df3a33.JPG)

**Comment by HarisIqbal88** [comment]
Hi, I was not aware of this behaviour. Also, there is no particular reason to use this way of creating labels. You can use node or other options mentioned in [#7](https://github.com/HarisIqbal88/PlotNeuralNet/issues/7#issuecomment-449911742)

**Comment by martinlindstrom** [comment]
Hi @HarisIqbal88 and cheers for a lovely package, it has saved me much headache drawing neural networks. 

I also see the black dot with Texmaker (PDFLaTeX) on Ubuntu when I am not using a caption for a Box. I found that if you comment out the following three lines from Box.sty the problem disappears.

> \tikzstyle{captionlabel}=[text width=15*\LastEastx/\scale,text centered]    
\path (\LastEastx/2,-\y/2,+\z/2) + (0,-25pt) coordinate (cap) 
edge ["\textcolor{black}{ \bf \caption}"',captionlabel](cap) ; %Block caption/pic object label
