### ISSUE TITLE
Fully Connected layer box

### ISSUE THREAD

**Issue by chrismaliszewski** [HarisIqbal88/PlotNeuralNet#82]
Below is the code that implements a fully connected layer box since I wasn't able to find it in the code. I used to_SoftMax function and modified it.

The code should be put inside pycore/tikzeng.py file.

```# Fully Connected
def to_FullyConnected( name, s_filer=" ", n_filer=" ", offset="(0,0,0)", to="(0,0,0)", width=1.5, height=3, depth=25, opacity=0.8, caption=" " , zlabelposition='midway'):
    return r"""
\pic[shift={"""+ offset +"""}] at """+ to +""" 
    {Box={
        name=""" + name +""",
        caption=""" +caption + """,
        xlabel={{ """+ '"'+str(n_filer) +'", "dummy"'+ """ }},
        zlabel="""+ str(s_filer) +""",
        zlabelposition="""+zlabelposition+""",
        fill=\FcColor,
        bandfill=\FcReluColor,
        opacity="""+ str(opacity) +""",
        height="""+ str(height) +""",
        width="""+ str(width) +""",
        depth="""+ str(depth) +"""
        }
    };
"""
```

Cheers.

**Comment by nachoraposo** [comment]
You are the real MVP. Saved me a couple hours making it myself <3

**Comment by pc-mysql** [comment]
very grateful

**Comment by Sanjeev906** [comment]
"Box=" should be "RightBandedBox" or it will say " I do not know the key '/tikz/bandfill'"

**Comment by 2243108785** [comment]
>  Package pgfkeys Error: I do not know the key '/tikz/zlabelposition', to which
 you passed 'midway', and I am going to ignore it. Perhaps you misspelled it.

**Comment by matthijsvk** [comment]
I also have this "I do not know the key '/tikz/zlabelposition', to which you passed 'midway'" error.

**Comment by Chocolita** [comment]
I delete the zlabelposition='midway' in the function, together with the line "zlabelposition="""+zlabelposition+"""," and it works for me.
