### ISSUE TITLE
Importing Standalone output to tex document

### ISSUE THREAD

**Issue by aklyussef** [HarisIqbal88/PlotNeuralNet#95]
Hey, 
Thanks for the tool, the graphics look awesome. I'm having some difficulty importing the outputted standalone tex file into a technical report of mine and was wondering if someone tried to do something similar and can help :)
Thanks!

**Comment by Etshhh** [comment]
If you could share with us how you added it to your report, that would be great!

**Comment by aklyussef** [comment]
I copied the pdf output from the tikzmake.sh script to a folder in my report filetree and added it in a figure block as shown below! No need to use the generated latex output from the script.

`\begin{figure}[htpb]                                                      
     \centering
       \includegraphics[width=0.8\linewidth]{intro/figures/Unet_ushape}
       \caption{UNet Architecture}%
       \label{fig:unet}
  \end{figure}`

**Comment by Etshhh** [comment]
That worked perfectly, thank you.

**Comment by chengengliu** [comment]
So we are importing the generated pdf file as a figure, is that correct?

**Comment by Etshhh** [comment]
yup, exactly.
